security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          users:
                a:  { password: a, roles: 'ROLE_ADMIN' }

    firewalls:    
      main:
        pattern: /.*
        form_login:
            check_path: /login_check
            login_path: /login
        logout:
            path: /logout
            target: /
        security: true
        anonymous: true

    access_control:
        - { path: /admin.*, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }