<?php

namespace Gaudruere\GiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	 /**
	  * Liste des articles
	  * 
	  * Instruction utilisée pour retrouver tous les articles de tous les sous-menus de ce root menu     
	  *     	  
	  */    	 
	public function findByPermalienMenu($permalienMenu)
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
		->from('GaudruereGiteBundle:Article', 'a')
		->join('a.menu','m','WITH','m.menuParent=:titreMenu')
		->setParameter('titreMenu', $permalienMenu) 
		->orderBy('m.ordre', 'asc');
		
		return $qb->getQuery()->getResult();
 	}	

	public function getArticleByPermalien($permalienArticle)
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
		->from('GaudruereGiteBundle:Article', 'a')
		->from('GaudruereGiteBundle:Menu', 'm')
		->where($qb->expr()->andx(
		$qb->expr()->eq('a.titre','m.titre'),
		$qb->expr()->eq('m.nom',':titreMenu')
		))
		->setParameter('titreMenu', $permalienArticle);

		return $qb->getQuery()->getSingleResult();
	}
          
	public function findByIdMenu($idMenu)
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a')
		->from('GaudruereGiteBundle:Article', 'a')    
		->join('a.menu','m','WITH','m.id=:id')
		->setParameter('id', $idMenu)
		->orderBy('a.ordre');
		
		return $qb->getQuery()->getResult();
    //		return $qb->getQuery()->getSingleResult();
 	}	

	
	
	
}