<?php

namespace Gaudruere\GiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametresRepository extends EntityRepository
{      
	public function findUniqueParametre()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('p')
		->from('GaudruereGiteBundle:Parametres', 'p');
		return $qb->getQuery()->getSingleResult();
 	}	
}