<?php

namespace Gaudruere\GiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	
	public function findAllReservationValidee($dateDebut, $dateFin)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('r')
		->from('GaudruereGiteBundle:Reservation', 'r')
		->where(
			$qb->expr()->andX(
				$qb->expr()->eq("r.reservationValidee", "1"),
				$qb->expr()->orX(
					$qb->expr()->between("r.dateDebut", "'" . $dateDebut . "'", "'" . $dateFin . "'"),
					$qb->expr()->between("r.dateFin", "'" . $dateDebut . "'", "'" . $dateFin . "'"),
					$qb->expr()->andX(
						$qb->expr()->lt("r.dateDebut", "'" . $dateDebut . "'"),
						$qb->expr()->gt("r.dateFin", "'" . $dateFin . "'")
					)
				)
			)
		)
		->orderBy('r.dateDebut');
		
		return $qb->getQuery()->getResult();
	}
}